"""03_add_models

Revision ID: 3916dc938a0d
Revises: 4221d34a0f2e
Create Date: 2023-05-16 18:27:38.439883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3916dc938a0d'
down_revision = '4221d34a0f2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('original_url', sa.String(length=1024), nullable=True),
    sa.Column('short_url', sa.String(length=64), nullable=True),
    sa.Column('number_of_use', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_url'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
