"""02_add_models

Revision ID: 4221d34a0f2e
Revises: 0222c93bd178
Create Date: 2023-05-16 18:24:58.699205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4221d34a0f2e'
down_revision = '0222c93bd178'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
