"""04_update_url_model

Revision ID: f14da077acab
Revises: 3916dc938a0d
Create Date: 2023-05-18 14:27:12.590395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14da077acab'
down_revision = '3916dc938a0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('url_short_url_key', 'url', type_='unique')
    op.drop_column('url', 'short_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('short_url', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint('url_short_url_key', 'url', ['short_url'])
    # ### end Alembic commands ###
